2021-05-03T10:55:55.962708+00:00 app[web.1]: worker.init_process()
2021-05-03T10:55:55.962709+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-05-03T10:55:55.962709+00:00 app[web.1]: self.load_wsgi()
2021-05-03T10:55:55.962710+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-05-03T10:55:55.962710+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2021-05-03T10:55:55.962711+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-05-03T10:55:55.962711+00:00 app[web.1]: self.callable = self.load()
2021-05-03T10:55:55.962711+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-05-03T10:55:55.962712+00:00 app[web.1]: return self.load_wsgiapp()
2021-05-03T10:55:55.962712+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-05-03T10:55:55.962713+00:00 app[web.1]: return util.import_app(self.app_uri)
2021-05-03T10:55:55.962713+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2021-05-03T10:55:55.962713+00:00 app[web.1]: mod = importlib.import_module(module)
2021-05-03T10:55:55.962714+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-05-03T10:55:55.962714+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2021-05-03T10:55:55.962715+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-05-03T10:55:55.962715+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-05-03T10:55:55.962716+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-05-03T10:55:55.962716+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-05-03T10:55:55.962717+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-05-03T10:55:55.962717+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-05-03T10:55:55.962717+00:00 app[web.1]: File "/app/boutique_ado/wsgi.py", line 16, in <module>
2021-05-03T10:55:55.962718+00:00 app[web.1]: application = get_wsgi_application()
2021-05-03T10:55:55.962718+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2021-05-03T10:55:55.962719+00:00 app[web.1]: django.setup(set_prefix=False)
2021-05-03T10:55:55.962719+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
2021-05-03T10:55:55.962719+00:00 app[web.1]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2021-05-03T10:55:55.962720+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
2021-05-03T10:55:55.962720+00:00 app[web.1]: self._setup(name)
2021-05-03T10:55:55.962721+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
2021-05-03T10:55:55.962721+00:00 app[web.1]: self._wrapped = Settings(settings_module)
2021-05-03T10:55:55.962722+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
2021-05-03T10:55:55.962722+00:00 app[web.1]: mod = importlib.import_module(self.SETTINGS_MODULE)
2021-05-03T10:55:55.962723+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-05-03T10:55:55.962723+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2021-05-03T10:55:55.962724+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-05-03T10:55:55.962724+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-05-03T10:55:55.962724+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-05-03T10:55:55.962725+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-05-03T10:55:55.962725+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-05-03T10:55:55.962726+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-05-03T10:55:55.962726+00:00 app[web.1]: File "/app/boutique_ado/settings.py", line 116, in <module>
2021-05-03T10:55:55.962726+00:00 app[web.1]: 'default': dj_database_url.parse(os.environ('DATABASE_URL'))
2021-05-03T10:55:55.962727+00:00 app[web.1]: TypeError: '_Environ' object is not callable
2021-05-03T10:55:55.963215+00:00 app[web.1]: [2021-05-03 10:55:55 +0000] [8] [INFO] Worker exiting (pid: 8)
2021-05-03T10:55:55.967081+00:00 app[web.1]: [2021-05-03 10:55:55 +0000] [7] [ERROR] Exception in worker process
2021-05-03T10:55:55.967083+00:00 app[web.1]: Traceback (most recent call last):
2021-05-03T10:55:55.967084+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2021-05-03T10:55:55.967085+00:00 app[web.1]: worker.init_process()
2021-05-03T10:55:55.967085+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-05-03T10:55:55.967085+00:00 app[web.1]: self.load_wsgi()
2021-05-03T10:55:55.967086+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-05-03T10:55:55.967086+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2021-05-03T10:55:55.967087+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-05-03T10:55:55.967087+00:00 app[web.1]: self.callable = self.load()
2021-05-03T10:55:55.967088+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-05-03T10:55:55.967088+00:00 app[web.1]: return self.load_wsgiapp()
2021-05-03T10:55:55.967088+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-05-03T10:55:55.967089+00:00 app[web.1]: return util.import_app(self.app_uri)
2021-05-03T10:55:55.967089+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2021-05-03T10:55:55.967089+00:00 app[web.1]: mod = importlib.import_module(module)
2021-05-03T10:55:55.967090+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-05-03T10:55:55.967090+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2021-05-03T10:55:55.967091+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-05-03T10:55:55.967092+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-05-03T10:55:55.967092+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-05-03T10:55:55.967092+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-05-03T10:55:55.967093+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-05-03T10:55:55.967093+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-05-03T10:55:55.967094+00:00 app[web.1]: File "/app/boutique_ado/wsgi.py", line 16, in <module>
2021-05-03T10:55:55.967095+00:00 app[web.1]: application = get_wsgi_application()
2021-05-03T10:55:55.967095+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2021-05-03T10:55:55.967095+00:00 app[web.1]: django.setup(set_prefix=False)
2021-05-03T10:55:55.967096+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
2021-05-03T10:55:55.967096+00:00 app[web.1]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2021-05-03T10:55:55.967097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
2021-05-03T10:55:55.967097+00:00 app[web.1]: self._setup(name)
2021-05-03T10:55:55.967097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
2021-05-03T10:55:55.967098+00:00 app[web.1]: self._wrapped = Settings(settings_module)
2021-05-03T10:55:55.967098+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
2021-05-03T10:55:55.967099+00:00 app[web.1]: mod = importlib.import_module(self.SETTINGS_MODULE)
2021-05-03T10:55:55.967099+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-05-03T10:55:55.967100+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2021-05-03T10:55:55.967100+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-05-03T10:55:55.967101+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-05-03T10:55:55.967101+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-05-03T10:55:55.967102+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-05-03T10:55:55.967102+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-05-03T10:55:55.967103+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-05-03T10:55:55.967103+00:00 app[web.1]: File "/app/boutique_ado/settings.py", line 116, in <module>
2021-05-03T10:55:55.967103+00:00 app[web.1]: 'default': dj_database_url.parse(os.environ('DATABASE_URL'))
2021-05-03T10:55:55.967104+00:00 app[web.1]: TypeError: '_Environ' object is not callable
2021-05-03T10:55:55.967581+00:00 app[web.1]: [2021-05-03 10:55:55 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-05-03T10:55:56.109717+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=anindita-boutique-ado.herokuapp.com request_id=da8f4a2b-a223-41ec-8737-bfee65dd8071 fwd="109.57.82.39" dyno=web.1 connect=1ms service=258ms status=503 bytes=0 protocol=https
2021-05-03T10:55:56.131946+00:00 app[web.1]: [2021-05-03 10:55:56 +0000] [4] [WARNING] Worker with pid 7 was terminated due to signal 15
2021-05-03T10:55:56.214282+00:00 app[web.1]: [2021-05-03 10:55:56 +0000] [4] [INFO] Shutting down: Master
2021-05-03T10:55:56.216913+00:00 app[web.1]: [2021-05-03 10:55:56 +0000] [4] [INFO] Reason: Worker failed to boot.
2021-05-03T10:55:56.447421+00:00 heroku[web.1]: Process exited with status 3
2021-05-03T10:55:56.544724+00:00 heroku[web.1]: State changed from up to crashed
2021-05-03T10:56:01.511379+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=anindita-boutique-ado.herokuapp.com request_id=410d1f94-ef34-45f1-b5eb-f64d9b5c3897 fwd="109.57.82.39" dyno=web.1 connect=5001ms service= status=503 bytes= protocol=https
